apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ticketa
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: ticketa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: ticketa
            - name: POSTGRES_PASSWORD
              value: ticketa
          volumeMounts:
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-script
          configMap:
            name: postgres-init
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: ticketa
data:
  init.sql: |
    CREATE DATABASE auth_db;
    CREATE DATABASE inventory_db;
    CREATE DATABASE payment_db;
    CREATE DATABASE ticket_db;
    CREATE DATABASE notification_db;
