apiVersion: v1
kind: Service
metadata:
  name: inventory-seat-service
  namespace: ticketa
spec:
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    app: inventory-seat-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-seat-service
  namespace: ticketa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-seat-service
  template:
    metadata:
      labels:
        app: inventory-seat-service
    spec:
      containers:
        - name: inventory-seat-service
          image: ticketa/inventory-seat-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:8761/eureka/
            - name: DB_R2DBC_URL
              value: r2dbc:postgresql://postgres:5432/inventory_db
            - name: DB_JDBC_URL
              value: jdbc:postgresql://postgres:5432/inventory_db
            - name: DB_USERNAME
              value: ticketa
            - name: DB_PASSWORD
              value: ticketa
            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: MANAGEMENT_OTLP_TRACING_ENDPOINT
              value: http://otel-collector:4318/v1/traces
