apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: ticketa
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: auth-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: ticketa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: ticketa/auth-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:8761/eureka/
            - name: DB_R2DBC_URL
              value: r2dbc:postgresql://postgres:5432/auth_db
            - name: DB_JDBC_URL
              value: jdbc:postgresql://postgres:5432/auth_db
            - name: DB_USERNAME
              value: ticketa
            - name: DB_PASSWORD
              value: ticketa
            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: MANAGEMENT_OTLP_TRACING_ENDPOINT
              value: http://otel-collector:4318/v1/traces
