global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'discovery-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['discovery-server:8761']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-service:8081']

  - job_name: 'ai-intent-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ai-intent-service:8082']

  - job_name: 'inventory-seat-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['inventory-seat-service:8083']

  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['payment-service:8084']

  - job_name: 'ticket-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ticket-service:8085']

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8086']
